### ISSUE TITLE
Error: Fw and Bw lkl do not match!

### ISSUE THREAD

**Issue by cbossu** [fgvieira/ngsF-HMM#3]
Hello,
 I'm running into the error regarding likelihood check: "Fw and Bw lkl do not match!" and "Numerical result out of range". Given the code is from the below chunk of code, and it's coded as a likelihood check due to precision issues on large datasets, I'm curious about what is considered a large data set. I'm trying to run this on 14 individuals with 6x coverage.  I'm attempting to see how ngsFHMM works with 6X coverage, compared to other programs to identify runs of homozygosity (those that require called genotypes). 

Do I need to subsample the bam files we have to lower coverage to allow this program to work? Can I adjust the 0.001 to a smaller number?

Thanks.

Christen

 // Lkl check! - relaxed (to 0.001) due to precision issues on large datasets
  for (uint64_t i = 0; i < pars->n_ind; i++)
    if( abs(logsum(Fw[i][pars->n_sites],2) - logsum(Bw[i][0],2)) > 0.001 ){
      printf("Ind %lu: %.15f\t%.15f (%.15f)\n", i, logsum(Fw[i][pars->n_sites],2), logsum(Bw[i][0],2), abs(logsum(Fw[i][pars->n_sites],2) - logsum(Bw[i][0],2)) );
      error(__FUNCTION__, "Fw and Bw lkl do not match!");
    }

**Comment by fgvieira** [comment]
Hi Christen,

14 indiv at 6x coverage should be fine... how are you running ngsF-HMM?
Can you send me the log file?

**Comment by cbossu** [comment]
Hello Filipe,
	I’ve attached the error file (*.err) and the log file (*.out). If you want the script, I can send that too. Best,

Christen


Christen Bossu
The Institute of the Environment and Sustainability 
Center for Tropical Research
University of California, Los Angeles
Los Angeles, CA 90095-1496
cbossu@ucla.edu

**Comment by fgvieira** [comment]
HI Christen,

where did you attach the files?
if not too big, you can also just copy/paste them directly here.

**Comment by cbossu** [comment]
Sorry. The files had .err and .out extensions, which wasn't supported by github. I've re-added them here with appropriate extensions. Best,

Christen
[BUOW.ngsFHMM.7897975.out.txt](https://github.com/fgvieira/ngsF-HMM/files/4282424/BUOW.ngsFHMM.7897975.out.txt)
[BUOW.ngsFHMM.7897975.err.txt](https://github.com/fgvieira/ngsF-HMM/files/4282425/BUOW.ngsFHMM.7897975.err.txt)

**Comment by fgvieira** [comment]
It looks like you are running `angsd` to get the 10 GL (option `-doGlf 4`), but that format is not supported by `ngsF-HMM`. Try running `angsd` with `-doGlf 2` and run `ngsF-HMM` without the `--loglkl` option.
