### ISSUE TITLE
Add individual names using ngsF-HMMplot.R

### ISSUE THREAD

**Issue by mpalmada** [fgvieira/ngsF-HMM#8]
Hi,

I wanted to know how to add the respective individual names in the plots generated with ngsF-HMMplot.R. (now I only get NAs)

Thanks a lot,

Marc

**Comment by fgvieira** [comment]
See:

https://github.com/fgvieira/ngsF-HMM/blob/2df96905f0d6df7ec021c4c27cc5bfc9c7f662c7/scripts/ngsF-HMMplot.R#L73

**Comment by mpalmada** [comment]
Hi,

Thanks a lot! This works! I would change the description to "File with per-row individual names to add in the resulting plots. It has to match the number of individuals.". I didn't understand it the first time I read it!

Thank you so much I close the issue!!

Marc
